### ISSUE TITLE
buildings missing

### ISSUE THREAD

**Issue by JoergFF** [giggls/openstreetmap-carto-de#16] opened 2016-09-27 05:22 UTC
Hi,

einige Gebäude werden nicht gezeichnet. Im Beispiel stehen die Hausnummern (56, 64) ohne Gebäude in der Landschaft.

![fehlende gebaude lieser moselstrasse](https://cloud.githubusercontent.com/assets/7426044/18861106/fb06fe4c-8482-11e6-8c39-d1534838e5c8.png)

**Comment by giggls** [comment] 2016-09-27 07:27
I guess I would need  to write some guiedlines for issue rreporting. First of all: Do not report here if the problem also exists on upstream. Second.: Please always include a tile URL or link to http://openstreetmap.de/karte.html otherwise I will not be able to reproduce the problem.

**Comment by giggls** [comment] 2016-09-27 08:18
OK, found it by Streetname query. Looks like fore some reason, these houses are missing from my database. Time slot looks suggests, that these houses have been created in a changeset I missed during initial database import. As this is not a bug in the stile though I will close this now.

**Closed by giggls** 2016-09-27 08:18 UTC
